-- v1.5.5 Reclamation loot: источники для предметов, потерявших их при порте.
-- Веса намеренно низкие; вставка через хелпер с guard'ом на несуществующие списки.

local recl_ArmyStorageAmmunition = {
    "Hydrocraft.HCBulletcasings", 1,
    "Hydrocraft.HCBullettips", 1,
    "Hydrocraft.HCBuckshot", 1,
}
insertItemListsInProcDistribution("ArmyStorageAmmunition", { recl_ArmyStorageAmmunition });

local recl_ButcherFreezer = {
    "Hydrocraft.HCDogmeat", 0.5,
    "Hydrocraft.HCCatmeat", 0.5,
    "Hydrocraft.HCSheepmeat", 0.5,
    "Hydrocraft.HCGoatmeat", 0.5,
    "Hydrocraft.HCPigmeat", 0.5,
    "Hydrocraft.HCCowmeat", 0.5,
    "Hydrocraft.HCCowmeat2", 0.5,
    "Hydrocraft.HCDonkeymeat", 0.5,
    "Hydrocraft.HCHorsemeat", 0.5,
    "Hydrocraft.HCNutriameat", 0.5,
    "Hydrocraft.HCBeavermeat", 0.5,
    "Hydrocraft.HCPorcupinemeat", 0.5,
    "Hydrocraft.HCArmadillomeat", 0.5,
    "Hydrocraft.HCFoxmeat", 0.5,
    "Hydrocraft.HCRaccoonmeat", 0.5,
    "Hydrocraft.HCOpossummeat", 0.5,
    "Hydrocraft.HCSkunkmeat", 0.5,
    "Hydrocraft.HCBoarmeat", 0.5,
    "Hydrocraft.HCDeermeat", 0.5,
    "Hydrocraft.HCDeermeat2", 0.5,
    "Hydrocraft.HCBlackbearmeat", 0.5,
    "Hydrocraft.HCBearmeat", 0.5,
    "Hydrocraft.HCCougarmeat", 0.5,
    "Hydrocraft.HCCheval", 0.5,
    "Hydrocraft.HCFreshham", 0.5,
}
insertItemListsInProcDistribution("ButcherFreezer", { recl_ButcherFreezer });

local recl_CampingStoreGear = {
    "Hydrocraft.HCFannypackblue", 0.5,
    "Hydrocraft.HCFannypackyellow", 0.5,
    "Hydrocraft.HCFannypackred", 0.5,
    "Hydrocraft.HCFannypackgreen", 0.5,
    "Hydrocraft.HCDuralumincase", 0.5,
    "Hydrocraft.HCSeedbag", 0.5,
    "Hydrocraft.HCToychest", 0.5,
    "Hydrocraft.HCChest", 0.5,
    "Hydrocraft.HCShipcrate1", 0.5,
    "Hydrocraft.HCShipcrate2", 0.5,
    "Hydrocraft.HCShipcrate3", 0.5,
    "Hydrocraft.HCShipcrate4", 0.5,
    "Hydrocraft.HCShipcrate5", 0.5,
    "Hydrocraft.HCShipcrate6", 0.5,
    "Hydrocraft.HCShipcrate7", 0.5,
    "Hydrocraft.HCFishingkitbroken", 1,
    "Hydrocraft.HCFishhookcopper", 1,
    "Hydrocraft.HCFishhooktin", 1,
    "Hydrocraft.HCFishhookbronze", 1,
    "Hydrocraft.HCFishhookiron", 1,
    "Hydrocraft.HCFishhooksteel", 1,
    "Hydrocraft.HCFishhookaluminum", 1,
    "Hydrocraft.HCFishhooktitanium", 1,
    "Hydrocraft.HCEggbass", 1,
    "Hydrocraft.HCEggcatfish", 1,
    "Hydrocraft.HCEggcrappie", 1,
    "Hydrocraft.HCEggpanfish", 1,
    "Hydrocraft.HCEggperch", 1,
    "Hydrocraft.HCEggpike", 1,
    "Hydrocraft.HCEggtrout", 1,
}
insertItemListsInProcDistribution("CampingStoreGear", { recl_CampingStoreGear });

local recl_CrateMetalwork = {
    "Hydrocraft.HCJeepLeft", 0.2,
    "Hydrocraft.HCJeepLeftDirty", 0.2,
    "Hydrocraft.HCJeepRight", 0.2,
    "Hydrocraft.HCJeepRightDirty", 0.2,
    "Hydrocraft.HCTractorL", 0.2,
    "Hydrocraft.HCTractorR", 0.2,
    "Hydrocraft.HCCar1L", 0.2,
    "Hydrocraft.HCCar1R", 0.2,
    "Hydrocraft.HCCar2L", 0.2,
    "Hydrocraft.HCCar2R", 0.2,
    "Hydrocraft.HCCar3L", 0.2,
    "Hydrocraft.HCCar3R", 0.2,
    "Hydrocraft.HCCar4L", 0.2,
    "Hydrocraft.HCCar4R", 0.2,
    "Hydrocraft.HCCar5L", 0.2,
    "Hydrocraft.HCCar5R", 0.2,
    "Hydrocraft.HCCar6L", 0.2,
    "Hydrocraft.HCCar6R", 0.2,
    "Hydrocraft.HCCar7L", 0.2,
    "Hydrocraft.HCCar7R", 0.2,
    "Hydrocraft.HCCar8L", 0.2,
    "Hydrocraft.HCCar8R", 0.2,
    "Hydrocraft.HCCar9L", 0.2,
    "Hydrocraft.HCCar9R", 0.2,
    "Hydrocraft.HCCar10L", 0.2,
    "Hydrocraft.HCCar10R", 0.2,
    "Hydrocraft.HCCar11L", 0.2,
    "Hydrocraft.HCCar11R", 0.2,
    "Hydrocraft.HCCar12L", 0.2,
    "Hydrocraft.HCCar12R", 0.2,
    "Hydrocraft.HCMotorcycle", 0.2,
    "Hydrocraft.HCFishhookbone", 1,
    "Hydrocraft.HCShellpowder", 1,
    "Hydrocraft.HCBoneneedle", 1,
    "Hydrocraft.HCGluejar", 1,
    "Hydrocraft.HCWoodgluejar", 1,
    "Hydrocraft.HCCompost", 1,
    "Hydrocraft.HCGlasspane", 1,
    "Hydrocraft.HCMicroscopeslide", 1,
    "Hydrocraft.HCWineglass", 1,
    "Hydrocraft.HCGreybrickbox", 1,
    "Hydrocraft.HCRefractorybrick", 1,
    "Hydrocraft.HCInvaringot", 1,
    "Hydrocraft.HCSteelingot", 1,
    "Hydrocraft.HCSSpringSteelIngot", 1,
    "Hydrocraft.HCPewteringot", 1,
    "Hydrocraft.HCElectrumingot", 1,
    "Hydrocraft.HCConstantaningot", 1,
    "Hydrocraft.HCNichromeingot", 1,
    "Hydrocraft.HCKanthalingot", 1,
    "Hydrocraft.HCTitaniumingot", 1,
    "Hydrocraft.HCCauldroniron", 1,
    "Hydrocraft.HCBulletcasings", 1,
    "Hydrocraft.HCBullettips", 1,
    "Hydrocraft.HCBuckshot", 1,
    "Hydrocraft.HCIngotmold", 1,
    "Hydrocraft.HCBungmold", 1,
    "Hydrocraft.HCGiantmagnetmold", 1,
    "Hydrocraft.HCBowBoltMold", 1,
    "Hydrocraft.HCArrowheadMold", 1,
    "Hydrocraft.HCClayflowerpot", 1,
    "Hydrocraft.HCClayjarsmall", 1,
    "Hydrocraft.HCClaycauldron", 1,
    "Hydrocraft.HCClayurn", 1,
    "Hydrocraft.HCWaxrecycled", 1,
    "Hydrocraft.HCLeafSpring", 1,
    "Hydrocraft.HCIronrod", 1,
    "Hydrocraft.HCSteelrod", 1,
    "Hydrocraft.HCTitaniumrod", 1,
    "Hydrocraft.HCGraphiterod", 1,
    "Hydrocraft.HCSteelpole", 1,
    "Hydrocraft.HCMetalring", 1,
    "Hydrocraft.HCTinboard", 1,
    "Hydrocraft.HCIronboard", 1,
    "Hydrocraft.HCSteelboard", 1,
    "Hydrocraft.HCTitaniumsheet", 1,
    "Hydrocraft.HCTitaniumsheetlarge", 1,
    "Hydrocraft.HCSawstone", 1,
    "Hydrocraft.HCChisel", 1,
    "Hydrocraft.HCWell", 1,
    "Hydrocraft.HCStonewheel", 1,
    "Hydrocraft.HCWoodenbucketsand", 1,
}
insertItemListsInProcDistribution("CrateMetalwork", { recl_CrateMetalwork });

local recl_CrateTools = {
    "Hydrocraft.HCLeatherstripfine", 0.5,
    "Hydrocraft.HCLeatherstriphard", 0.5,
    "Hydrocraft.HCBeltbuckle", 0.5,
    "Hydrocraft.HCHidelimedrabbit", 0.5,
    "Hydrocraft.HCHidelimedsquirrel", 0.5,
    "Hydrocraft.HCHidelimedgroundhog", 0.5,
    "Hydrocraft.HCHidelimedmuskrat", 0.5,
    "Hydrocraft.HCHidelimednutria", 0.5,
    "Hydrocraft.HCHidelimedbeaver", 0.5,
    "Hydrocraft.HCHidelimedarmadillo", 0.5,
    "Hydrocraft.HCHidelimedfox", 0.5,
    "Hydrocraft.HCHidelimedopossum", 0.5,
    "Hydrocraft.HCHidelimedskunk", 0.5,
    "Hydrocraft.HCHidelimedraccoon", 0.5,
    "Hydrocraft.HCHidelimedboar", 0.5,
    "Hydrocraft.HCHidelimeddeer", 0.5,
    "Hydrocraft.HCHidelimedbearblack", 0.5,
    "Hydrocraft.HCHidelimedbear", 0.5,
    "Hydrocraft.HCHidelimedcougar", 0.5,
    "Hydrocraft.HCHidelimeddog", 0.5,
    "Hydrocraft.HCHidelimedcat", 0.5,
    "Hydrocraft.HCHidelimedsheep", 0.5,
    "Hydrocraft.HCHidelimedgoat", 0.5,
    "Hydrocraft.HCHidelimedpig", 0.5,
    "Hydrocraft.HCHidelimedcow", 0.5,
    "Hydrocraft.HCHidelimedbull", 0.5,
    "Hydrocraft.HCHidelimeddonkey", 0.5,
    "Hydrocraft.HCHidelimedhorse", 0.5,
    "Hydrocraft.HCWaterflaskfull", 0.5,
}
insertItemListsInProcDistribution("CrateTools", { recl_CrateTools });

local recl_GarageTools = {
    "Hydrocraft.HCJeepLeft", 0.2,
    "Hydrocraft.HCJeepLeftDirty", 0.2,
    "Hydrocraft.HCJeepRight", 0.2,
    "Hydrocraft.HCJeepRightDirty", 0.2,
    "Hydrocraft.HCTractorL", 0.2,
    "Hydrocraft.HCTractorR", 0.2,
    "Hydrocraft.HCCar1L", 0.2,
    "Hydrocraft.HCCar1R", 0.2,
    "Hydrocraft.HCCar2L", 0.2,
    "Hydrocraft.HCCar2R", 0.2,
    "Hydrocraft.HCCar3L", 0.2,
    "Hydrocraft.HCCar3R", 0.2,
    "Hydrocraft.HCCar4L", 0.2,
    "Hydrocraft.HCCar4R", 0.2,
    "Hydrocraft.HCCar5L", 0.2,
    "Hydrocraft.HCCar5R", 0.2,
    "Hydrocraft.HCCar6L", 0.2,
    "Hydrocraft.HCCar6R", 0.2,
    "Hydrocraft.HCCar7L", 0.2,
    "Hydrocraft.HCCar7R", 0.2,
    "Hydrocraft.HCCar8L", 0.2,
    "Hydrocraft.HCCar8R", 0.2,
    "Hydrocraft.HCCar9L", 0.2,
    "Hydrocraft.HCCar9R", 0.2,
    "Hydrocraft.HCCar10L", 0.2,
    "Hydrocraft.HCCar10R", 0.2,
    "Hydrocraft.HCCar11L", 0.2,
    "Hydrocraft.HCCar11R", 0.2,
    "Hydrocraft.HCCar12L", 0.2,
    "Hydrocraft.HCCar12R", 0.2,
    "Hydrocraft.HCMotorcycle", 0.2,
    "Hydrocraft.HCObsidianpowder", 0.3,
    "Hydrocraft.HCSilveriodidepowder", 0.3,
    "Hydrocraft.HCCopperoxidepowder", 0.3,
    "Hydrocraft.HCCoppersulfatepowder", 0.3,
    "Hydrocraft.HCNickelsulfatepowder", 0.3,
    "Hydrocraft.HCSodiumsulfatpowder", 0.3,
    "Hydrocraft.HCCitricacid", 0.3,
    "Hydrocraft.HCPlasticcanammonia", 0.5,
    "Hydrocraft.HCPlasticcancoppersulfatesolution", 0.5,
    "Hydrocraft.HCPlasticcandetergent", 0.5,
    "Hydrocraft.HCPlasticcanlime", 0.5,
    "Hydrocraft.HCPlasticcanlye", 0.5,
    "Hydrocraft.HCPlasticcanmethanol", 0.5,
    "Hydrocraft.HCPlasticcanmilk", 0.5,
    "Hydrocraft.HCPlasticcanoil", 0.5,
    "Hydrocraft.HCPlasticcanrose", 0.5,
    "Hydrocraft.HCPlasticcansulfuricacid", 0.5,
    "Hydrocraft.HCPlasticcantan", 0.5,
    "Hydrocraft.HCPlasticcanhoney", 0.5,
    "Hydrocraft.HCPlasticcanpoison", 0.5,
    "Hydrocraft.HCPlasticcanwater", 0.5,
    "Hydrocraft.HCDrillhand", 1,
    "Hydrocraft.HCBackscratcher", 1,
    "Hydrocraft.HCShoehorn", 1,
    "Hydrocraft.HCPortableminingmachinepowered", 1,
    "Hydrocraft.HCPortableminingmachinedead", 1,
    "Hydrocraft.HCElectricmultitoolpowered", 1,
    "Hydrocraft.HCElectricmultitooldead", 1,
    "Hydrocraft.HCNailclip", 1,
    "Hydrocraft.HCMonkeywrench", 1,
    "Hydrocraft.HCPickaxe", 1,
    "Hydrocraft.ChainSaw", 1,
    "Hydrocraft.ChainSawNoGas", 1,
}
insertItemListsInProcDistribution("GarageTools", { recl_GarageTools });

local recl_GigamartDryGoods = {
    "Hydrocraft.HCHaircolorbrunette", 0.5,
    "Hydrocraft.HCBodybrush", 0.5,
    "Hydrocraft.HCHairconditioner", 0.5,
    "Hydrocraft.HCToiletpaperpack", 0.5,
    "Hydrocraft.HCSanitizingjar", 0.5,
    "Hydrocraft.HCFannypackblue", 0.5,
    "Hydrocraft.HCFannypackyellow", 0.5,
    "Hydrocraft.HCFannypackred", 0.5,
    "Hydrocraft.HCFannypackgreen", 0.5,
    "Hydrocraft.HCDuralumincase", 0.5,
    "Hydrocraft.HCSeedbag", 0.5,
    "Hydrocraft.HCToychest", 0.5,
    "Hydrocraft.HCChest", 0.5,
    "Hydrocraft.HCShipcrate1", 0.5,
    "Hydrocraft.HCShipcrate2", 0.5,
    "Hydrocraft.HCShipcrate3", 0.5,
    "Hydrocraft.HCShipcrate4", 0.5,
    "Hydrocraft.HCShipcrate5", 0.5,
    "Hydrocraft.HCShipcrate6", 0.5,
    "Hydrocraft.HCShipcrate7", 0.5,
}
insertItemListsInProcDistribution("GigamartDryGoods", { recl_GigamartDryGoods });

local recl_GigamartToys = {
    "Hydrocraft.HCBabybottle", 0.5,
    "Hydrocraft.HCBabybib1", 0.5,
    "Hydrocraft.HCBabybib2", 0.5,
    "Hydrocraft.HCBirdie", 0.5,
    "Hydrocraft.HCHokeypuck", 0.5,
    "Hydrocraft.HCTennisracket", 0.5,
    "Hydrocraft.HCWifflebat", 0.5,
}
insertItemListsInProcDistribution("GigamartToys", { recl_GigamartToys });

local recl_LibraryCounter = {
    "Hydrocraft.HCComic1", 0.5,
    "Hydrocraft.HCComic2", 0.5,
    "Hydrocraft.HCComic3", 0.5,
    "Hydrocraft.HCComic4", 0.5,
    "Hydrocraft.HCComic5", 0.5,
    "Hydrocraft.HCComic6", 0.5,
    "Hydrocraft.HCComic7", 0.5,
    "Hydrocraft.HCComic8", 0.5,
    "Hydrocraft.HCComic9", 0.5,
    "Hydrocraft.HCVinylrecord1", 0.5,
    "Hydrocraft.HCVinylrecord2", 0.5,
    "Hydrocraft.HCVinylrecord3", 0.5,
    "Hydrocraft.HCVinylrecord4", 0.5,
    "Hydrocraft.HCVinylrecord5", 0.5,
    "Hydrocraft.Banjo", 0.5,
    "Hydrocraft.HCElectricguitar", 0.5,
    "Hydrocraft.HCElectricguitarbass", 0.5,
    "Hydrocraft.HCGuitarpick", 0.5,
    "Hydrocraft.HCAmp", 0.5,
    "Hydrocraft.HCDrumkit", 0.5,
    "Hydrocraft.HCPiano", 0.5,
    "Hydrocraft.HCPianogrand", 0.5,
}
insertItemListsInProcDistribution("LibraryCounter", { recl_LibraryCounter });

local recl_MechanicShelfMisc = {
    "Hydrocraft.HCPlasticcanammonia", 0.5,
    "Hydrocraft.HCPlasticcancoppersulfatesolution", 0.5,
    "Hydrocraft.HCPlasticcandetergent", 0.5,
    "Hydrocraft.HCPlasticcanlime", 0.5,
    "Hydrocraft.HCPlasticcanlye", 0.5,
    "Hydrocraft.HCPlasticcanmethanol", 0.5,
    "Hydrocraft.HCPlasticcanmilk", 0.5,
    "Hydrocraft.HCPlasticcanoil", 0.5,
    "Hydrocraft.HCPlasticcanrose", 0.5,
    "Hydrocraft.HCPlasticcansulfuricacid", 0.5,
    "Hydrocraft.HCPlasticcantan", 0.5,
    "Hydrocraft.HCPlasticcanhoney", 0.5,
    "Hydrocraft.HCPlasticcanpoison", 0.5,
    "Hydrocraft.HCPlasticcanwater", 0.5,
}
insertItemListsInProcDistribution("MechanicShelfMisc", { recl_MechanicShelfMisc });

local recl_PoliceStorageOutfit = {
    "Hydrocraft.HCHelmbike", 1,
    "Hydrocraft.HCHelmfootball", 1,
    "Hydrocraft.HCHockeymask", 1,
    "Hydrocraft.HCHelmkevlar", 1,
    "Hydrocraft.HCHelmswat", 1,
    "Hydrocraft.HCHelmriot", 1,
    "Hydrocraft.HCHelmsamurai", 1,
    "Hydrocraft.HCGlovekevlar", 1,
    "Hydrocraft.HCGloveriot", 1,
    "Hydrocraft.HCGlovecord", 1,
    "Hydrocraft.HCArmarmorkevlar", 1,
    "Hydrocraft.HCArmarmorswat", 1,
    "Hydrocraft.HCArmarmorriot", 1,
    "Hydrocraft.HCArmarmorpaintball", 1,
    "Hydrocraft.HCArmarmorsamurai", 1,
    "Hydrocraft.HCArmormilitaryjacket", 1,
    "Hydrocraft.HCArmorlightjacket", 1,
    "Hydrocraft.HCArmorleatherjacket", 1,
    "Hydrocraft.HCArmorkevlar", 1,
    "Hydrocraft.HCArmorswat", 1,
    "Hydrocraft.HCArmorriot", 1,
    "Hydrocraft.HCArmorpaintball", 1,
    "Hydrocraft.HCArmorsamurai", 1,
    "Hydrocraft.HCArmorphonebooks", 1,
    "Hydrocraft.HCJeans", 1,
    "Hydrocraft.HCLegarmorkevlar", 1,
    "Hydrocraft.HCLegarmorswat", 1,
    "Hydrocraft.HCLegarmorriot", 1,
    "Hydrocraft.HCLegarmorpaintball", 1,
    "Hydrocraft.HCLegarmorsamurai", 1,
    "Hydrocraft.HCShieldriot", 1,
    "Hydrocraft.HCShieldtrashcanlid", 1,
}
insertItemListsInProcDistribution("PoliceStorageOutfit", { recl_PoliceStorageOutfit });

local recl_PostOfficeBooks = {
    "Hydrocraft.HCComic1", 0.5,
    "Hydrocraft.HCComic2", 0.5,
    "Hydrocraft.HCComic3", 0.5,
    "Hydrocraft.HCComic4", 0.5,
    "Hydrocraft.HCComic5", 0.5,
    "Hydrocraft.HCComic6", 0.5,
    "Hydrocraft.HCComic7", 0.5,
    "Hydrocraft.HCComic8", 0.5,
    "Hydrocraft.HCComic9", 0.5,
}
insertItemListsInProcDistribution("PostOfficeBooks", { recl_PostOfficeBooks });

local recl_RandomFiller = {
    "Hydrocraft.HCBook", 0.3,
    "Hydrocraft.HCPassport", 0.3,
    "Hydrocraft.Nothing_Random_Book", 0.3,
    "Hydrocraft.HCQueenbee", 0.3,
    "Hydrocraft.HCBeehive3bActive", 0.3,
    "Hydrocraft.HCBeehive3full", 0.3,
    "Hydrocraft.HCBeehive3bfull", 0.3,
    "Hydrocraft.HCBluebarreltoxicwaste", 0.3,
    "Hydrocraft.HCBatterysixpack", 0.3,
    "Hydrocraft.HCBeakerh2o2hexacitricacidcooled", 0.3,
    "Hydrocraft.HCPropanetankempty", 0.3,
    "Hydrocraft.HCBlueprintflamethrower", 0.3,
    "Hydrocraft.HCLeech", 0.3,
    "Hydrocraft.HCLeechbloated", 0.3,
    "Hydrocraft.HCCanteenfull", 0.3,
    "Hydrocraft.HCRaftrubber", 0.3,
    "Hydrocraft.HCPaddlemetal", 0.3,
    "Hydrocraft.HCCandleholder", 0.3,
    "Hydrocraft.HCTroughfull", 0.3,
    "Hydrocraft.HCWatertowerfull2", 0.3,
    "Hydrocraft.HCWaterpump2", 0.3,
    "Hydrocraft.HCYoke", 0.3,
    "Hydrocraft.HCFoldingsignchalkboard", 0.3,
    "Hydrocraft.HCElectrolyzer", 0.3,
    "Hydrocraft.HCCheeserackaged", 0.3,
    "Hydrocraft.HCCheeserackagedcheddar", 0.3,
    "Hydrocraft.HCCheeserackagedcheddarwaxed", 0.3,
    "Hydrocraft.HCSmokedsalmoncreamcheesesandwich", 0.3,
    "Hydrocraft.HCFeatherduster", 0.3,
    "Hydrocraft.HCFabricsoftener", 0.3,
    "Hydrocraft.HCWashboard", 0.3,
    "Hydrocraft.HCBroom", 0.3,
    "Hydrocraft.HCPushbroom", 0.3,
    "Hydrocraft.HCImprovisedhazmat", 0.3,
    "Hydrocraft.HCBarrelLemonFermented", 0.3,
    "Hydrocraft.HCAgavebluecut", 0.3,
    "Hydrocraft.HCPotofblueagavemashcooked", 0.3,
    "Hydrocraft.HCBongdirty", 0.3,
    "Hydrocraft.HCBongacrylicdirty", 0.3,
    "Hydrocraft.HCPureopium", 0.3,
    "Hydrocraft.HCSyringeheroin", 0.3,
    "Hydrocraft.HCRadioantenna", 0.3,
    "Hydrocraft.HCVacuumtube", 0.3,
    "Hydrocraft.HCFirehose", 0.3,
    "Hydrocraft.HCFirehosenozzle", 0.3,
    "Hydrocraft.HCFirehook", 0.3,
    "Hydrocraft.HCFlagpolepurple", 0.3,
    "Hydrocraft.HCFlagpoleblue", 0.3,
    "Hydrocraft.HCFlagpolegreen", 0.3,
    "Hydrocraft.HCFlagpoleyellow", 0.3,
    "Hydrocraft.HCFlagpoleorange", 0.3,
    "Hydrocraft.HCFlagpolered", 0.3,
    "Hydrocraft.HCMezcalworm", 0.3,
    "Hydrocraft.HCBBQsmallbird", 0.3,
    "Hydrocraft.HCFrostedchristmascookie", 0.3,
    "Hydrocraft.HCFrostedchristmascookietray", 0.3,
    "Hydrocraft.HCMilkjugwater", 0.3,
    "Hydrocraft.HCMilkjugchocolatewater", 0.3,
    "Hydrocraft.HCWhippedcreamcanRotten", 0.3,
    "Hydrocraft.HCJarhomemadeyogurtcranberries", 0.3,
    "Hydrocraft.HCDriedapple", 0.3,
    "Hydrocraft.HCDriedpeach", 0.3,
    "Hydrocraft.HCDriedorange", 0.3,
    "Hydrocraft.HCDriedlemon", 0.3,
    "Hydrocraft.HCDriedlime", 0.3,
    "Hydrocraft.HCDriedbananachips", 0.3,
    "Hydrocraft.HCDriedstrawberryslices", 0.3,
    "Hydrocraft.HCDriedberries", 0.3,
    "Hydrocraft.HCDriedtomato", 0.3,
    "Hydrocraft.HCDriedpumpkinseeds", 0.3,
    "Hydrocraft.HCDriedrasins", 0.3,
    "Hydrocraft.HCDriedcrasins", 0.3,
    "Hydrocraft.HCFrenchtoast", 0.3,
    "Hydrocraft.HCBreadwheatloafbag", 0.3,
    "Hydrocraft.HCBreadwheat", 0.3,
    "Hydrocraft.HCBreadwheatslices", 0.3,
    "Hydrocraft.HCJelloapple1cold", 0.3,
    "Hydrocraft.HCJelloblueberry1cold", 0.3,
    "Hydrocraft.HCJellocherry1cold", 0.3,
    "Hydrocraft.HCJellolemon1cold", 0.3,
    "Hydrocraft.HCJelloorange1cold", 0.3,
    "Hydrocraft.HCJellolime1cold", 0.3,
    "Hydrocraft.HCJellowatermelon1cold", 0.3,
    "Hydrocraft.HCJellostrawberry1cold", 0.3,
    "Hydrocraft.HCMREpoundcake", 0.3,
    "Hydrocraft.HCCottoncandy", 0.3,
    "Hydrocraft.HCSaltedcheval", 0.3,
    "Hydrocraft.HCFishoil", 0.3,
    "Hydrocraft.HCSmoker", 0.3,
    "Hydrocraft.HCChilipot", 0.3,
    "Hydrocraft.HCJalapeno", 0.3,
    "Hydrocraft.HCHops", 0.3,
    "Hydrocraft.HCTeafresh", 0.3,
    "Hydrocraft.HCDeskbell", 0.3,
    "Hydrocraft.HCTriphammer2", 0.3,
    "Hydrocraft.HCLavalamp", 0.3,
    "Hydrocraft.HCLighterempty", 0.3,
    "Hydrocraft.HCBoxholiday", 0.3,
    "Hydrocraft.HCBrokenHearingaid", 0.3,
    "Hydrocraft.HCDissectiontablebody", 0.3,
    "Hydrocraft.HCDissectiontablebloody", 0.3,
    "Hydrocraft.HCBodybag", 0.3,
    "Hydrocraft.HCPetribiowaste", 0.3,
    "Hydrocraft.HCPetrinothing", 0.3,
    "Hydrocraft.HCPiggybank", 0.3,
    "Hydrocraft.HCSlotmachine", 0.3,
    "Hydrocraft.HCRoulette", 0.3,
    "Hydrocraft.HCVinylrecord1", 0.5,
    "Hydrocraft.HCVinylrecord2", 0.5,
    "Hydrocraft.HCVinylrecord3", 0.5,
    "Hydrocraft.HCVinylrecord4", 0.5,
    "Hydrocraft.HCVinylrecord5", 0.5,
    "Hydrocraft.Banjo", 0.5,
    "Hydrocraft.HCElectricguitar", 0.5,
    "Hydrocraft.HCElectricguitarbass", 0.5,
    "Hydrocraft.HCGuitarpick", 0.5,
    "Hydrocraft.HCAmp", 0.5,
    "Hydrocraft.HCDrumkit", 0.5,
    "Hydrocraft.HCPiano", 0.5,
    "Hydrocraft.HCPianogrand", 0.5,
    "Hydrocraft.HCBlackink", 0.3,
    "Hydrocraft.HCBlackink0", 0.3,
    "Hydrocraft.HCPoisonwater", 0.3,
    "Hydrocraft.HCHandcuffs", 0.3,
    "Hydrocraft.HCPolicebadge", 0.3,
    "Hydrocraft.HCBaton", 0.3,
    "Hydrocraft.HCDetergentwater", 0.3,
    "Hydrocraft.HCSelfmadesolarpanel", 0.3,
    "Hydrocraft.HCTabletskinanimal", 0.3,
    "Hydrocraft.HCSpindlehead", 0.3,
    "Hydrocraft.HCWool", 0.3,
    "Hydrocraft.HCCloth", 0.3,
    "Hydrocraft.HCThimble", 0.3,
    "Hydrocraft.HCPlastichanger", 0.3,
    "Hydrocraft.HCMittens", 0.3,
    "Hydrocraft.HCClotheslinefull", 0.3,
    "Hydrocraft.HCClotheslinefull2", 0.3,
    "Hydrocraft.HCSocksWoolAnkle", 0.3,
    "Hydrocraft.HCSocksWoolLong", 0.3,
    "Hydrocraft.HCBoneButton", 0.3,
    "Hydrocraft.PropaneTrapCloses", 0.3,
    "Hydrocraft.BearTrapClosed", 0.3,
    "Hydrocraft.SpikeTrapClosed", 0.3,
    "Hydrocraft.spanishRider", 0.3,
    "Hydrocraft.HCPop2trash", 0.5,
    "Hydrocraft.HCPop3trash", 0.5,
    "Hydrocraft.HCTincanwater", 0.5,
    "Hydrocraft.HCERFBtrashbag", 0.5,
    "Hydrocraft.HCMREempty", 0.5,
    "Hydrocraft.HCMREmealsideprepedtrash", 0.5,
    "Hydrocraft.HCCandybar1trash", 0.5,
    "Hydrocraft.HCCandybar2trash", 0.5,
    "Hydrocraft.HCCandybar3trash", 0.5,
    "Hydrocraft.HCCandybar4trash", 0.5,
    "Hydrocraft.HCCheesecrackerstrash", 0.5,
    "Hydrocraft.HCHelicopterL", 0.3,
    "Hydrocraft.HCHelicopterR", 0.3,
    "Hydrocraft.HCTicketBF", 0.3,
    "Hydrocraft.HCTicketCR", 0.3,
    "Hydrocraft.HCTicketND", 0.3,
    "Hydrocraft.HCTicketVS", 0.3,
    "Hydrocraft.HCTicketOR", 0.3,
    "Hydrocraft.HCTicketMI", 0.3,
    "Hydrocraft.HCArrowAttachment", 0.3,
    "Hydrocraft.HCHomemadebatcrudetentpegs", 0.3,
    "Hydrocraft.HCHomemadebattentpegs", 0.3,
    "Hydrocraft.HCBaseballbattentpegs", 0.3,
    "Hydrocraft.HCHomemadeclubcrudetentpegs", 0.3,
    "Hydrocraft.HCHomemadeclubtentpegs", 0.3,
    "Hydrocraft.HCMasterclubtentpegs", 0.3,
    "Hydrocraft.HCGrenade", 0.3,
    "Hydrocraft.HCBarrelwine", 0.3,
    "Hydrocraft.HCBarrelwinewhite", 0.3,
    "Hydrocraft.HCBarrelvinegar", 0.3,
    "Hydrocraft.HCBarrelmead", 0.3,
    "Hydrocraft.HCBarrelsake", 0.3,
}
insertItemListsInProcDistribution("RandomFiller", { recl_RandomFiller });

local recl_SecurityStorage = {
    "Hydrocraft.HCHelmbike", 1,
    "Hydrocraft.HCHelmfootball", 1,
    "Hydrocraft.HCHockeymask", 1,
    "Hydrocraft.HCHelmkevlar", 1,
    "Hydrocraft.HCHelmswat", 1,
    "Hydrocraft.HCHelmriot", 1,
    "Hydrocraft.HCHelmsamurai", 1,
    "Hydrocraft.HCGlovekevlar", 1,
    "Hydrocraft.HCGloveriot", 1,
    "Hydrocraft.HCGlovecord", 1,
    "Hydrocraft.HCArmarmorkevlar", 1,
    "Hydrocraft.HCArmarmorswat", 1,
    "Hydrocraft.HCArmarmorriot", 1,
    "Hydrocraft.HCArmarmorpaintball", 1,
    "Hydrocraft.HCArmarmorsamurai", 1,
    "Hydrocraft.HCArmormilitaryjacket", 1,
    "Hydrocraft.HCArmorlightjacket", 1,
    "Hydrocraft.HCArmorleatherjacket", 1,
    "Hydrocraft.HCArmorkevlar", 1,
    "Hydrocraft.HCArmorswat", 1,
    "Hydrocraft.HCArmorriot", 1,
    "Hydrocraft.HCArmorpaintball", 1,
    "Hydrocraft.HCArmorsamurai", 1,
    "Hydrocraft.HCArmorphonebooks", 1,
    "Hydrocraft.HCJeans", 1,
    "Hydrocraft.HCLegarmorkevlar", 1,
    "Hydrocraft.HCLegarmorswat", 1,
    "Hydrocraft.HCLegarmorriot", 1,
    "Hydrocraft.HCLegarmorpaintball", 1,
    "Hydrocraft.HCLegarmorsamurai", 1,
    "Hydrocraft.HCShieldriot", 1,
    "Hydrocraft.HCShieldtrashcanlid", 1,
}
insertItemListsInProcDistribution("SecurityStorage", { recl_SecurityStorage });

local recl_StoreCounterTobacco = {
    "Hydrocraft.HCBarrelLemonFermented", 0.3,
    "Hydrocraft.HCAgavebluecut", 0.3,
    "Hydrocraft.HCPotofblueagavemashcooked", 0.3,
    "Hydrocraft.HCBarrelwine", 0.3,
    "Hydrocraft.HCBarrelwinewhite", 0.3,
    "Hydrocraft.HCBarrelvinegar", 0.3,
    "Hydrocraft.HCBarrelmead", 0.3,
    "Hydrocraft.HCBarrelsake", 0.3,
}
insertItemListsInProcDistribution("StoreCounterTobacco", { recl_StoreCounterTobacco });

local recl_StoreKitchenBaking = {
    "Hydrocraft.HCCoffeefilterpapertowel", 0.5,
    "Hydrocraft.HCAlestienfull", 0.5,
    "Hydrocraft.HCPlasticspoonbox", 0.5,
    "Hydrocraft.HCPlasticforkbox", 0.5,
    "Hydrocraft.HCPlasticknifebox", 0.5,
    "Hydrocraft.HCPlasticcoffeespoon", 0.5,
    "Hydrocraft.HCPlasticcupfull", 0.5,
    "Hydrocraft.HCStyrofoamcupfull", 0.5,
    "Hydrocraft.HCTray", 0.5,
    "Hydrocraft.HCTray2", 0.5,
    "Hydrocraft.HCMenu", 0.5,
    "Hydrocraft.HCSterlingsilverfork", 0.5,
    "Hydrocraft.HCSterlingsilverspoon", 0.5,
    "Hydrocraft.HCSterlingsilverknife", 0.5,
}
insertItemListsInProcDistribution("StoreKitchenBaking", { recl_StoreKitchenBaking });

local recl_StoreKitchenDishes = {
    "Hydrocraft.HCCoffeefilterpapertowel", 1,
    "Hydrocraft.HCAlestienfull", 1,
    "Hydrocraft.HCPlasticspoonbox", 1,
    "Hydrocraft.HCPlasticforkbox", 1,
    "Hydrocraft.HCPlasticknifebox", 1,
    "Hydrocraft.HCPlasticcoffeespoon", 1,
    "Hydrocraft.HCPlasticcupfull", 1,
    "Hydrocraft.HCStyrofoamcupfull", 1,
    "Hydrocraft.HCTray", 1,
    "Hydrocraft.HCTray2", 1,
    "Hydrocraft.HCMenu", 1,
    "Hydrocraft.HCSterlingsilverfork", 1,
    "Hydrocraft.HCSterlingsilverspoon", 1,
    "Hydrocraft.HCSterlingsilverknife", 1,
}
insertItemListsInProcDistribution("StoreKitchenDishes", { recl_StoreKitchenDishes });

local recl_StoreShelfMedical = {
    "Hydrocraft.HCHaircolorbrunette", 0.5,
    "Hydrocraft.HCBodybrush", 0.5,
    "Hydrocraft.HCHairconditioner", 0.5,
    "Hydrocraft.HCToiletpaperpack", 0.5,
    "Hydrocraft.HCSanitizingjar", 0.5,
    "Hydrocraft.HCObsidianpowder", 0.3,
    "Hydrocraft.HCSilveriodidepowder", 0.3,
    "Hydrocraft.HCCopperoxidepowder", 0.3,
    "Hydrocraft.HCCoppersulfatepowder", 0.3,
    "Hydrocraft.HCNickelsulfatepowder", 0.3,
    "Hydrocraft.HCSodiumsulfatpowder", 0.3,
    "Hydrocraft.HCCitricacid", 0.3,
    "Hydrocraft.HCGlasswaterbottle", 0.5,
    "Hydrocraft.HCHydrogentankempty", 0.5,
    "Hydrocraft.HCHeliumtankempty", 0.5,
    "Hydrocraft.HCOxygentankempty", 0.5,
    "Hydrocraft.HCHclgastankempty", 0.5,
    "Hydrocraft.HCTankfridge", 0.5,
    "Hydrocraft.HCTankfridgeempty", 0.5,
    "Hydrocraft.HCLabbig2", 0.5,
}
insertItemListsInProcDistribution("StoreShelfMedical", { recl_StoreShelfMedical });

local recl_ToolStoreMetalwork = {
    "Hydrocraft.HCFishhookbone", 1,
    "Hydrocraft.HCShellpowder", 1,
    "Hydrocraft.HCBoneneedle", 1,
    "Hydrocraft.HCGluejar", 1,
    "Hydrocraft.HCWoodgluejar", 1,
    "Hydrocraft.HCCompost", 1,
    "Hydrocraft.HCGlasspane", 1,
    "Hydrocraft.HCMicroscopeslide", 1,
    "Hydrocraft.HCWineglass", 1,
    "Hydrocraft.HCGreybrickbox", 1,
    "Hydrocraft.HCRefractorybrick", 1,
    "Hydrocraft.HCInvaringot", 1,
    "Hydrocraft.HCSteelingot", 1,
    "Hydrocraft.HCSSpringSteelIngot", 1,
    "Hydrocraft.HCPewteringot", 1,
    "Hydrocraft.HCElectrumingot", 1,
    "Hydrocraft.HCConstantaningot", 1,
    "Hydrocraft.HCNichromeingot", 1,
    "Hydrocraft.HCKanthalingot", 1,
    "Hydrocraft.HCTitaniumingot", 1,
    "Hydrocraft.HCCauldroniron", 1,
    "Hydrocraft.HCBulletcasings", 1,
    "Hydrocraft.HCBullettips", 1,
    "Hydrocraft.HCBuckshot", 1,
    "Hydrocraft.HCIngotmold", 1,
    "Hydrocraft.HCBungmold", 1,
    "Hydrocraft.HCGiantmagnetmold", 1,
    "Hydrocraft.HCBowBoltMold", 1,
    "Hydrocraft.HCArrowheadMold", 1,
    "Hydrocraft.HCClayflowerpot", 1,
    "Hydrocraft.HCClayjarsmall", 1,
    "Hydrocraft.HCClaycauldron", 1,
    "Hydrocraft.HCClayurn", 1,
    "Hydrocraft.HCWaxrecycled", 1,
    "Hydrocraft.HCLeafSpring", 1,
    "Hydrocraft.HCIronrod", 1,
    "Hydrocraft.HCSteelrod", 1,
    "Hydrocraft.HCTitaniumrod", 1,
    "Hydrocraft.HCGraphiterod", 1,
    "Hydrocraft.HCSteelpole", 1,
    "Hydrocraft.HCMetalring", 1,
    "Hydrocraft.HCTinboard", 1,
    "Hydrocraft.HCIronboard", 1,
    "Hydrocraft.HCSteelboard", 1,
    "Hydrocraft.HCTitaniumsheet", 1,
    "Hydrocraft.HCTitaniumsheetlarge", 1,
    "Hydrocraft.HCSawstone", 1,
    "Hydrocraft.HCChisel", 1,
    "Hydrocraft.HCWell", 1,
    "Hydrocraft.HCStonewheel", 1,
    "Hydrocraft.HCWoodenbucketsand", 1,
}
insertItemListsInProcDistribution("ToolStoreMetalwork", { recl_ToolStoreMetalwork });

local recl_ToolStoreTools = {
    "Hydrocraft.HCLeatherstripfine", 0.5,
    "Hydrocraft.HCLeatherstriphard", 0.5,
    "Hydrocraft.HCBeltbuckle", 0.5,
    "Hydrocraft.HCHidelimedrabbit", 0.5,
    "Hydrocraft.HCHidelimedsquirrel", 0.5,
    "Hydrocraft.HCHidelimedgroundhog", 0.5,
    "Hydrocraft.HCHidelimedmuskrat", 0.5,
    "Hydrocraft.HCHidelimednutria", 0.5,
    "Hydrocraft.HCHidelimedbeaver", 0.5,
    "Hydrocraft.HCHidelimedarmadillo", 0.5,
    "Hydrocraft.HCHidelimedfox", 0.5,
    "Hydrocraft.HCHidelimedopossum", 0.5,
    "Hydrocraft.HCHidelimedskunk", 0.5,
    "Hydrocraft.HCHidelimedraccoon", 0.5,
    "Hydrocraft.HCHidelimedboar", 0.5,
    "Hydrocraft.HCHidelimeddeer", 0.5,
    "Hydrocraft.HCHidelimedbearblack", 0.5,
    "Hydrocraft.HCHidelimedbear", 0.5,
    "Hydrocraft.HCHidelimedcougar", 0.5,
    "Hydrocraft.HCHidelimeddog", 0.5,
    "Hydrocraft.HCHidelimedcat", 0.5,
    "Hydrocraft.HCHidelimedsheep", 0.5,
    "Hydrocraft.HCHidelimedgoat", 0.5,
    "Hydrocraft.HCHidelimedpig", 0.5,
    "Hydrocraft.HCHidelimedcow", 0.5,
    "Hydrocraft.HCHidelimedbull", 0.5,
    "Hydrocraft.HCHidelimeddonkey", 0.5,
    "Hydrocraft.HCHidelimedhorse", 0.5,
    "Hydrocraft.HCWaterflaskfull", 0.5,
    "Hydrocraft.HCDrillhand", 1,
    "Hydrocraft.HCBackscratcher", 1,
    "Hydrocraft.HCShoehorn", 1,
    "Hydrocraft.HCPortableminingmachinepowered", 1,
    "Hydrocraft.HCPortableminingmachinedead", 1,
    "Hydrocraft.HCElectricmultitoolpowered", 1,
    "Hydrocraft.HCElectricmultitooldead", 1,
    "Hydrocraft.HCNailclip", 1,
    "Hydrocraft.HCMonkeywrench", 1,
    "Hydrocraft.HCPickaxe", 1,
    "Hydrocraft.ChainSaw", 1,
    "Hydrocraft.ChainSawNoGas", 1,
}
insertItemListsInProcDistribution("ToolStoreTools", { recl_ToolStoreTools });
