-- Hydrocraft Reinvented [B42]: RU names for vanilla build-menu entities.
-- Mod translations merge AFTER vanilla scripts are parsed, so the cached
-- translationName of vanilla entity build recipes never sees our Recipes.json
-- keys. Re-apply them at boot via overrideTranslationName. Language-agnostic:
-- if the UI_ key is absent for the current language, nothing changes.

local NAMES = {
    "Advanced Forge",
    "Advanced Makeshift Electric Blower Forge",
    "Antlers Pole",
    "Arc Furnace",
    "Barbed Wire Fence",
    "Big Double Pole Gate",
    "Big Double Wire Gate",
    "Big Metal Locker",
    "Big Metal Locker (Shoddy)",
    "Big Metal Pole Fence",
    "Big Metal Wire Fence",
    "Big Pole Fence Gate",
    "Big Wire Fence Gate",
    "Blast Furnace",
    "Bottling Machine",
    "Brick Door Frame (Good)",
    "Brick Door Frame (Poor)",
    "Brick Fence (Good)",
    "Brick Pallet",
    "Brick Wall (Good)",
    "Brick Wall (Poor)",
    "Brick Window Frame",
    "Brick Window Frame (Poor)",
    "Bull Skull Pole",
    "Butcher Hook",
    "Charcoal Burner",
    "Charcoal Burning Pit",
    "Chicken Coop 1",
    "Chicken Coop 2",
    "Chopping Block",
    "Churn Bucket",
    "Coffee Machine",
    "Composter (Shoddy)",
    "Cooking Pit",
    "Cow Skull Pole",
    "Deer Skull Pole",
    "Dirt Floor",
    "Doe Skull Pole",
    "Dome Kiln",
    "Double Door",
    "Electric Blower Forge",
    "Fluid Separator",
    "Gold Pallet",
    "Gravel Floor",
    "Grinding Slab",
    "Hand Operated Press",
    "HayBundle",
    "Heckle Comb",
    "Hydraulic Press",
    "Juice Maker",
    "Key Duplicator",
    "Kiln Furnace",
    "Lamp On Pillar",
    "Large Drying Rack",
    "Large Kiln",
    "Large Pit of Coals",
    "Lean-To Shelter",
    "Leather Shelter",
    "Log Bench",
    "Log Door Frame (Poor)",
    "Log Fence",
    "Log Stairs",
    "Log Stool",
    "Log Stool 1",
    "Log Stool 2",
    "Log Table",
    "Log Wall",
    "Log Window Frame (Poor)",
    "Long Wood Feeding Trough",
    "Loom",
    "Makeshift Electric Blower Forge",
    "Medium Drying Rack",
    "Metal Bandsaw",
    "Metal Bar Barricade",
    "Metal Barrel Oven",
    "Metal Counter",
    "Metal Counter (Shoddy)",
    "Metal Counter Corner",
    "Metal Counter Corner (Shoddy)",
    "Metal Crate",
    "Metal Crate (Shoddy)",
    "Metal Door (Poor)",
    "Metal Door (Shoddy)",
    "Metal Door Frame (Good)",
    "Metal Door Frame (Poor)",
    "Metal Feeding Trough",
    "Metal Fence (Good)",
    "Metal Fence (Shoddy)",
    "Metal Floor",
    "Metal Sheet Barricade",
    "Metal Shelves",
    "Metal Shelves (Shoddy)",
    "Metal Stairs",
    "Metal Wall (Good)",
    "Metal Wall (Poor)",
    "Metal Wall Frame",
    "Metal Window Frame",
    "Metal Window Frame (Poor)",
    "Metalwork Lathe",
    "Metalwork Table",
    "Metalworkbench",
    "Piano",
    "Pig Skull Pole",
    "Pit of Coals",
    "Planks Barricade",
    "Pottery Bench",
    "Pottery Wheel",
    "Press",
    "Primitive Forge",
    "Primitive Furnace",
    "Rain Collector Barrel",
    "Rain Collector Barrel Tarp",
    "Rain Collector Crate",
    "Rain Collector Crate Tarp",
    "Ripple Comb",
    "Rugged Cross",
    "Rugged Stool",
    "Rugged Table",
    "Sand Floor",
    "Sandbag Wall",
    "Sawmill",
    "Scutching Board",
    "Sheep Skull Pole",
    "Short Log Bench",
    "Short Wood Feeding Trough",
    "Simple Cooking Pit",
    "Simple Loom",
    "Small Drying Rack",
    "Small Kiln",
    "Small Metal Locker",
    "Small Metal Locker (Shoddy)",
    "Small Metal Pole Fence (Poor)",
    "Small Metal Wire Fence",
    "Small Pole Fence Gate",
    "Small Wire Fence Gate",
    "Small Wood Table (Good)",
    "Small Wood Table (Poor)",
    "Small Wood Table (Shoddy)",
    "Smelting Furnace",
    "Softening Beam",
    "Spinning Wheel",
    "Standing Drill Press",
    "Steam Boiler",
    "Steam Turbine",
    "Stick Bookcase",
    "Stick Fence",
    "Stick Small Bookcase",
    "Stone Anvil",
    "Stone Cabinet",
    "Stone Door Frame",
    "Stone Mill",
    "Stone Quern",
    "Stone Wall",
    "Stone Window Frame",
    "Tannin Barrel",
    "Tarp Shelter",
    "Tile Floor",
    "Toaster",
    "Tree Stump",
    "Water Dispenser",
    "Water Pump",
    "Well",
    "Wide Log Gate",
    "Wood Bar Element (Good)",
    "Wood Bar Element (Poor)",
    "Wood Bar Element (Shoddy)",
    "Wood Bar Element Corner (Good)",
    "Wood Bar Element Corner (Poor)",
    "Wood Bar Element Corner (Shoddy)",
    "Wood Bookcase",
    "Wood Bookcase (Shoddy)",
    "Wood Chair (Good)",
    "Wood Chair (Poor)",
    "Wood Chair (Shoddy)",
    "Wood Crate",
    "Wood Crate (Shoddy)",
    "Wood Cross",
    "Wood Door (Good)",
    "Wood Door (Poor)",
    "Wood Door (Shoddy)",
    "Wood Door Frame (Good)",
    "Wood Door Frame (Poor)",
    "Wood Door Frame (Shoddy)",
    "Wood Double Shelves (Shoddy)",
    "Wood Fence (Good)",
    "Wood Fence (Poor)",
    "Wood Fence (Shoddy)",
    "Wood Fence Gate",
    "Wood Floor (Good)",
    "Wood Floor (Poor)",
    "Wood Floor (Shoddy)",
    "Wood Picket",
    "Wood Pole",
    "Wood Shelves",
    "Wood Shelves (Shoddy)",
    "Wood Sign",
    "Wood Small Bookcase",
    "Wood Small Bookcase (Shoddy)",
    "Wood Table",
    "Wood Table (Good)",
    "Wood Table (Poor)",
    "Wood Table (Shoddy)",
    "Wood Table with Drawer",
    "Wood Table with Drawer (Good)",
    "Wood Table with Drawer (Shoddy)",
    "Wood Wall (Shoddy)",
    "Wood Wall Frame",
    "Wood Window Frame (Good)",
    "Wood Window Frame (Poor)",
    "Wood Window Frame (Shoddy)",
    "Wooden Stairs",
    "Wooden Stake",
    "Wooden Wall (Good)",
    "Wooden Wall (Poor)",
    "Wooden Windows"
}

local function HCR_ApplyBuildMenuNames()
    local sm = getScriptManager()
    if not sm then return end
    for i = 1, #NAMES do
        local name = NAMES[i]
        local tr = getTextOrNull("UI_HCR_BM_" .. string.gsub(name, "%W", "_"))
        if tr then
            local recipe = sm:getCraftRecipe(name)
            if recipe and recipe.overrideTranslationName then
                recipe:overrideTranslationName(tr)
            end
        end
    end
end

Events.OnGameStart.Add(HCR_ApplyBuildMenuNames)
